apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  ports:
    - port: 80
      targetPort: vproapp-port # this is a port name defined in app deployment file
      protocol: TCP
  selector:
    app: vproapp
  type: LoadBalancer # its gonna launch elastic load balancer
